spring.application.name=backend

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/kfokam48}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jackson.deserialization.accept-float-as-int=false